### ISSUE TITLE
NMS issue

### ISSUE THREAD

**Issue by RoboMWM** [techfortress/Bukkit-CreativeItemControl#1]
As per @PhanaticD

```
[12:56:44 ERROR]: Could not pass event InventoryCreativeEvent to CreativeItemControl v1.12-SNAPSHOT-root
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-853]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-853]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-853]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-853]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-853]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2053) [patched_1.10.2.jar:git-Paper-853]
        at net.minecraft.server.v1_10_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [patched_1.10.2.jar:git-Paper-853]
        at net.minecraft.server.v1_10_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [patched_1.10.2.jar:git-Paper-853]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-853]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-853]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:804) [patched_1.10.2.jar:git-Paper-853]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-853]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:738) [patched_1.10.2.jar:git-Paper-853]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:637) [patched_1.10.2.jar:git-Paper-853]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassCastException: net.minecraft.server.v1_10_R1.NBTTagCompound cannot be cast to net.minecraft.server.v1_10_R1.NBTTagList
        at org.cyberiantiger.minecraft.unsafe.v1_10_R1.NBTTools.fromNativeList(NBTTools.java:311) ~[?:?]
        at org.cyberiantiger.minecraft.unsafe.v1_10_R1.NBTTools.fromNativeCompound(NBTTools.java:219) ~[?:?]
        at org.cyberiantiger.minecraft.unsafe.v1_10_R1.NBTTools.fromNativeCompound(NBTTools.java:204) ~[?:?]
        at org.cyberiantiger.minecraft.unsafe.v1_10_R1.NBTTools.fromNativeCompound(NBTTools.java:185) ~[?:?]
        at org.cyberiantiger.minecraft.unsafe.v1_10_R1.NBTTools.readItemStack(NBTTools.java:373) ~[?:?]
        at org.cyberiantiger.minecraft.itemcontrol.Main.onCreativeEvent(Main.java:233) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor305.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-853]
        ... 16 more
```

**Comment by RoboMWM** [comment]
So um idk how this happens, unable to reproduce.

**Comment by RoboMWM** [comment]
Ok this is probably why https://github.com/techfortress/Bukkit-CreativeItemControl/commit/d8a811088c69da727f9a8e79cd0fec5c1ad639a3

And thus is probably fixed maybe idk
